sylius_rbac_administration_role:
    resource: |
        alias: sylius_rbac.administration_role
        only: ['index']
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: sylius_rbac_administration_role
        redirect: update
    type: sylius.resource

sylius_rbac_admin_administration_role_create_view:
    path: /administration-roles/new
    methods: [GET]
    defaults:
        _controller: Odiseo\SyliusRbacPlugin\Action\CreateAdministrationRoleViewAction

sylius_rbac_admin_administration_role_create:
    path: /administration-roles/new
    methods: [PUT, PATCH]
    defaults:
        _controller: Odiseo\SyliusRbacPlugin\Action\CreateAdministrationRoleAction

sylius_rbac_admin_administration_role_update_view:
    path: /administration-roles/{id}/update
    methods: [GET]
    defaults:
        _controller: Odiseo\SyliusRbacPlugin\Action\UpdateAdministrationRoleViewAction

sylius_rbac_admin_administration_role_update:
    path: /administration-roles/{id}/update
    methods: [POST]
    defaults:
        _controller: Odiseo\SyliusRbacPlugin\Action\UpdateAdministrationRoleAction
